"""add exam metadata and enhanced question fields

Revision ID: 045679aaeb2e
Revises: 224f0bdede46
Create Date: 2025-12-16 13:27:56.557080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045679aaeb2e'
down_revision: Union[str, Sequence[str], None] = '224f0bdede46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('course_code', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('course_name', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('semester', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('exam_date', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('total_marks', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('exam_type', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('part', sa.String(length=10), nullable=True))
    op.add_column('questions', sa.Column('part_marks', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('question_number', sa.String(length=20), nullable=True))
    op.add_column('questions', sa.Column('is_mcq', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.String(length=10), nullable=True))
    op.add_column('questions', sa.Column('is_mandatory', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('has_or_option', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'has_or_option')
    op.drop_column('questions', 'is_mandatory')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'options')
    op.drop_column('questions', 'is_mcq')
    op.drop_column('questions', 'question_number')
    op.drop_column('questions', 'part_marks')
    op.drop_column('questions', 'part')
    op.drop_column('documents', 'exam_type')
    op.drop_column('documents', 'duration_minutes')
    op.drop_column('documents', 'total_marks')
    op.drop_column('documents', 'exam_date')
    op.drop_column('documents', 'semester')
    op.drop_column('documents', 'course_name')
    op.drop_column('documents', 'course_code')
    # ### end Alembic commands ###
