"""add unit field to questions

Revision ID: 6a01f4cd3e89
Revises: 045679aaeb2e
Create Date: 2025-12-16 13:40:03.422563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a01f4cd3e89'
down_revision: Union[str, Sequence[str], None] = '045679aaeb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('unit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'unit')
    # ### end Alembic commands ###
